name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *'  # Scheduled to run daily at midnight
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Python script
      run: python "Tropical Watch Tracking.py"
