name: Run Python Script and Update Data

on:
  schedule:
    - cron: '0 2 * * *'  # Scheduled to run daily at midnight
  workflow_dispatch:

jobs:
  run-script-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Python script
      run: python "watch_tracking.py"
