name: Run Python Script and Update Data

on:
  schedule:
    - cron: '0 */3 * * *'  # Scheduled to run daily at midnight
  workflow_dispatch:

jobs:
  run-script-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Adjust Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Timezone to Eastern Time
      run: sudo timedatectl set-timezone America/New_York
      
    - name: Execute Python script
      run: python "watch_tracking.py"

    - name: Commit and Push watch_data.json changes
      run: |
        git config --global user.name 'SebRGruber1'
        git config --global user.email 'sebastianrgruber@gmail.com'
        git add watch_data.json
        git commit -m "Update watch_data.json" || echo "No changes in watch_data.json"
        git push

    - name: Execute watch_report.py script
      run: python watch_report.py
      
    - name: Commit docs and portfoliop changes
      run: |
        git add docs/index.html docs/portfolio_value.png portfolio_statistics.json # Assuming the image is saved in the docs folder
        git commit -m "Update docs, portfolio image and portfolio statistics" || echo "No changes in docs or image or portfolio"
        git push

    - name: Reset Timezone to UTC
      run: sudo timedatectl set-timezone UTC
